name: CursebyteCore
version: 1.0
main: com.cursebyte.plugin.CursebyteCore
api-version: 1.20
commands:
  app:
    description: Membuka aplikasi nasional
    usage: /app

  setupimmigration:
    description: Atur lokasi spawn dan NPC imigrasi
    usage: /setupimmigration <spawn|npc>
    permission: immigration.admin

  setmoney:
    description: Menambahkan uang player
    usage: /setmoney <nama|uang> <uang>
    permission: economy.admin

  setreputation:
    description: Menambahkan reputasi player
    usage: /setmoney <nama|reputasi> <reputasi>
    permission: government.admin