name: CurseByteCore
version: 1.0
main: com.cursebyte.plugin.CursebyteCore
api-version: 1.20
commands:
  app:
    description: Membuka aplikasi nasional
    usage: /app

  setupimmigration:
    description: Atur lokasi spawn dan NPC imigrasi
    usage: /setupimmigration <spawn|npc>
    permission: immigration.admin